version: 2

project_name: elastic-docs-utils

before:
  hooks:
    - go mod tidy

builds:
  - id: elastic-docs-utils
    main: ./cmd/elastic-docs-utils
    binary: elastic-docs-utils
    ldflags:
      - -s -w -X main.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE.txt
      - NOTICE.txt
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: elastic
    name: docs-utils
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  footer: |
    ## Install

    ```bash
    curl -sSL https://ela.st/docs-utils-sh | bash
    ```

    Or on Windows (PowerShell):
    ```powershell
    irm https://ela.st/docs-utils-ps | iex
    ```
